version: '3'
services:
  api:
    build: api
    ports:
    - "8001:8001"
    environment:
      MONGO: mongodb://mongo:27017/
      BOOTSTRAP_SERVER: 10.168.5.96:9092
    volumes:
    - ./mount_data:/opt/logs
    links:
    - mongo
    
  mongo:
    image: bitnami/mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
    - "27017:27017"
  client:
    build: vue-admin
    ports:
    - "8002:8002"
    - "8003:8003"
    links:
    - api
volumes:
  mongo-data:
  mongo-configdb:
  # kafka-persistence: